//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class AnalystIdea2
    {
    	[DataMember]
        public int AnalystIdeaId { get; set; }
    	[DataMember]
        public int IssuerId { get; set; }
    	[DataMember]
        public bool IsLong { get; set; }
    	[DataMember]
        public System.DateTime EffectiveFromDate { get; set; }
    	[DataMember]
        public System.DateTime EffectiveToDate { get; set; }
    	[DataMember]
        public Nullable<int> AnalystId { get; set; }
    	[DataMember]
        public Nullable<int> OriginatiorId { get; set; }
    	[DataMember]
        public Nullable<int> FocusListId { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    
        [DataMember]
        public virtual ApplicationUser Analyst { get; set; }
        [DataMember]
        public virtual FocusList FocusList { get; set; }
        [DataMember]
        public virtual Issuer Issuer { get; set; }
        [DataMember]
        public virtual Originator Originator { get; set; }
    }
}
