//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Attribution
    {
    	[DataMember]
        public int AttributionID { get; set; }
    	[DataMember]
        public int PositionId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundAdministratorPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundAdministratorFX { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundAdministratorCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundAdministratorOther { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundKeeleyPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundKeeleyFX { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundKeeleyCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookKeeleyPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookKeeleyFX { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookKeeleyCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundValuationPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundValuationFX { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundValuationCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundFactsetPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundFactsetFX { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDFundFactsetCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookFactsetPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookFactsetFX { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookFactsetCarry { get; set; }
    	[DataMember]
        public decimal ITDFundPrice { get; set; }
    	[DataMember]
        public decimal ITDFundFX { get; set; }
    	[DataMember]
        public decimal ITDFundCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookFX { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDBookCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundAdministratorPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundAdministratorFX { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundAdministratorCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundAdministratorOther { get; set; }
    	[DataMember]
        public decimal TodayFundKeeleyPrice { get; set; }
    	[DataMember]
        public decimal TodayFundKeeleyFX { get; set; }
    	[DataMember]
        public decimal TodayFundKeeleyCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookKeeleyPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookKeeleyFX { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookKeeleyCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundValuationPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundValuationFX { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundValuationCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundFactsetPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundFactsetFX { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayFundFactsetCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookFactsetPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookFactsetFX { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookFactsetCarry { get; set; }
    	[DataMember]
        public decimal TodayFundPrice { get; set; }
    	[DataMember]
        public decimal TodayFundFX { get; set; }
    	[DataMember]
        public decimal TodayFundCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookFX { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayBookCarry { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public Nullable<int> PortfolioId { get; set; }
    	[DataMember]
        public Nullable<decimal> OpeningBookNav { get; set; }
    	[DataMember]
        public Nullable<decimal> CapitalChangeBook { get; set; }
    	[DataMember]
        public Nullable<decimal> OpeningFundNav { get; set; }
    	[DataMember]
        public Nullable<decimal> CapitalChangeFund { get; set; }
    	[DataMember]
        public Nullable<decimal> AdministratorOpeningNav { get; set; }
    	[DataMember]
        public Nullable<decimal> TotalContributionSinceLastValuation { get; set; }
    	[DataMember]
        public Nullable<decimal> OpeningValuationNav { get; set; }
    
        [DataMember]
        public virtual Position Position { get; set; }
        [DataMember]
        public virtual Portfolio Portfolio { get; set; }
    }
}
