//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Attribution
    {
    	[DataMember]
        public int AttributionID { get; set; }
    	[DataMember]
        public int PositionId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public Nullable<decimal> FundAdministratorPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> FundAdministratorFX { get; set; }
    	[DataMember]
        public Nullable<decimal> FundAdministratorCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> FundAdministratorOther { get; set; }
    	[DataMember]
        public decimal FundKeeleyPrice { get; set; }
    	[DataMember]
        public decimal FundKeeleyFX { get; set; }
    	[DataMember]
        public decimal FundKeeleyCarry { get; set; }
    	[DataMember]
        public decimal BookKeeleyPrice { get; set; }
    	[DataMember]
        public decimal BookKeeleyFX { get; set; }
    	[DataMember]
        public decimal BookKeeleyCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> FundFactsetPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> FundFactsetFX { get; set; }
    	[DataMember]
        public Nullable<decimal> FundFactsetCarry { get; set; }
    	[DataMember]
        public Nullable<decimal> BookFactsetPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> BookFactsetFX { get; set; }
    	[DataMember]
        public Nullable<decimal> BookFactsetCarry { get; set; }
    	[DataMember]
        public decimal FundPrice { get; set; }
    	[DataMember]
        public decimal FundFX { get; set; }
    	[DataMember]
        public decimal FundCarry { get; set; }
    	[DataMember]
        public decimal BookPrice { get; set; }
    	[DataMember]
        public decimal BookFX { get; set; }
    	[DataMember]
        public decimal BookCarry { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    }
}
