//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Client
    {
    	
        public Client()
        {
            this.ClientAccounts = new List<ClientAccount>();
        }
    
    	[DataMember]
        public int ClientId { get; set; }
    	[DataMember]
        public string ExternalReference { get; set; }
    	[DataMember]
        public int ClientSubTypeId { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public int CountryId { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public bool Unconfirmed { get; set; }
    
        [DataMember]
        public virtual List<ClientAccount> ClientAccounts { get; set; }
    }
}
