//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class EntityRankingSchemeOrder
    {
    	[DataMember]
        public int EntityRankingSchemeOrderId { get; set; }
    	[DataMember]
        public int EntityRankingSchemeId { get; set; }
    	[DataMember]
        public int EntityTypeId { get; set; }
    	[DataMember]
        public int EntityRankingSchemeItemId { get; set; }
    	[DataMember]
        public int Ordering { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public bool AlwaysStore { get; set; }
    
        [DataMember]
        public virtual EntityRankingSchemeItem EntityRankingSchemeItem { get; set; }
        [DataMember]
        public virtual EntityType EntityType { get; set; }
    }
}
