//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Odey.Framework.Keeley.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ExtractOutputConfiguration))]
    public partial class EntityProperty: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
        [DataMember]
        public int EntityPropertyID
        {	
    		
            get { return _entityPropertyID; }
            set
            {
                if (_entityPropertyID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'EntityPropertyID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _entityPropertyID = value;
                    OnPropertyChanged("EntityPropertyID");
                }
            }
        }
        private int _entityPropertyID;
        [DataMember]
        public int EntityTypeId
        {	
    		
            get { return _entityTypeId; }
            set
            {
                if (_entityTypeId != value)
                {
                    _entityTypeId = value;
                    OnPropertyChanged("EntityTypeId");
                }
            }
        }
        private int _entityTypeId;
        [DataMember]
        public bool NeedsToBeCalculated
        {	
    		
            get { return _needsToBeCalculated; }
            set
            {
                if (_needsToBeCalculated != value)
                {
                    _needsToBeCalculated = value;
                    OnPropertyChanged("NeedsToBeCalculated");
                }
            }
        }
        private bool _needsToBeCalculated;
        [DataMember]
        public string Name
        {	
    		
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
        [DataMember]
        public System.DateTime StartDt
        {	
    		
            get { return _startDt; }
            private set
            {
                if (_startDt != value)
                {
                    _startDt = value;
                    OnPropertyChanged("StartDt");
                }
            }
        }
        private System.DateTime _startDt;
        [DataMember]
        public int UpdateUserID
        {	
    		
            get { return _updateUserID; }
            private set
            {
                if (_updateUserID != value)
                {
                    ChangeTracker.RecordOriginalValue("UpdateUserID", _updateUserID);
                    _updateUserID = value;
                    OnPropertyChanged("UpdateUserID");
                }
            }
        }
        private int _updateUserID;
        [DataMember]
        private byte[] DataVersion
        {	
    		
            get { return _dataVersion; }
            set
            {
                if (_dataVersion != value)
                {
                    _dataVersion = value;
                    OnPropertyChanged("DataVersion");
                }
            }
        }
        private byte[] _dataVersion;
        [DataMember]
        public bool PropertyOnChildEntity
        {	
    		
            get { return _propertyOnChildEntity; }
            set
            {
                if (_propertyOnChildEntity != value)
                {
                    _propertyOnChildEntity = value;
                    OnPropertyChanged("PropertyOnChildEntity");
                }
            }
        }
        private bool _propertyOnChildEntity;
        [DataMember]
        public int TypeCode
        {	
    		
            get { return _typeCode; }
            set
            {
                if (_typeCode != value)
                {
                    _typeCode = value;
                    OnPropertyChanged("TypeCode");
                }
            }
        }
        private int _typeCode;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<ExtractOutputConfiguration> ExtractOutputConfigurations
        {
            get
            {
                if (_extractOutputConfigurations == null)
                {
                    _extractOutputConfigurations = new TrackableCollection<ExtractOutputConfiguration>();
                    _extractOutputConfigurations.CollectionChanged += FixupExtractOutputConfigurations;
                }
                return _extractOutputConfigurations;
            }
            set
            {
                if (!ReferenceEquals(_extractOutputConfigurations, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_extractOutputConfigurations != null)
                    {
                        _extractOutputConfigurations.CollectionChanged -= FixupExtractOutputConfigurations;
                    }
                    _extractOutputConfigurations = value;
                    if (_extractOutputConfigurations != null)
                    {
                        _extractOutputConfigurations.CollectionChanged += FixupExtractOutputConfigurations;
                    }
                    OnNavigationPropertyChanged("ExtractOutputConfigurations");
                }
            }
        }
        private TrackableCollection<ExtractOutputConfiguration> _extractOutputConfigurations;
    
        [DataMember]
        public TrackableCollection<ExtractOutputConfiguration> ExtractOutputConfigurations1
        {
            get
            {
                if (_extractOutputConfigurations1 == null)
                {
                    _extractOutputConfigurations1 = new TrackableCollection<ExtractOutputConfiguration>();
                    _extractOutputConfigurations1.CollectionChanged += FixupExtractOutputConfigurations1;
                }
                return _extractOutputConfigurations1;
            }
            set
            {
                if (!ReferenceEquals(_extractOutputConfigurations1, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_extractOutputConfigurations1 != null)
                    {
                        _extractOutputConfigurations1.CollectionChanged -= FixupExtractOutputConfigurations1;
                    }
                    _extractOutputConfigurations1 = value;
                    if (_extractOutputConfigurations1 != null)
                    {
                        _extractOutputConfigurations1.CollectionChanged += FixupExtractOutputConfigurations1;
                    }
                    OnNavigationPropertyChanged("ExtractOutputConfigurations1");
                }
            }
        }
        private TrackableCollection<ExtractOutputConfiguration> _extractOutputConfigurations1;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ExtractOutputConfigurations.Clear();
            ExtractOutputConfigurations1.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupExtractOutputConfigurations(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ExtractOutputConfiguration item in e.NewItems)
                {
                    item.EntityProperty = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ExtractOutputConfigurations", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ExtractOutputConfiguration item in e.OldItems)
                {
                    if (ReferenceEquals(item.EntityProperty, this))
                    {
                        item.EntityProperty = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ExtractOutputConfigurations", item);
                    }
                }
            }
        }
    
        private void FixupExtractOutputConfigurations1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ExtractOutputConfiguration item in e.NewItems)
                {
                    item.EntityPropertyToWrite = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ExtractOutputConfigurations1", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ExtractOutputConfiguration item in e.OldItems)
                {
                    if (ReferenceEquals(item.EntityPropertyToWrite, this))
                    {
                        item.EntityPropertyToWrite = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ExtractOutputConfigurations1", item);
                    }
                }
            }
        }

        #endregion
    }
}
