//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using TypeLite;
    [TsClass]
    [DataContract(IsReference = true)]
    public partial class ExtractOutputConfiguration
    {
    	[DataMember]
        public int ExtractOutputConfigurationID { get; set; }
    	[DataMember]
        public int ExtractId { get; set; }
    	[DataMember]
        public string Label { get; set; }
    	[DataMember]
        public bool ChangesCanBeIgnored { get; set; }
    	[DataMember]
        public int OrderBy { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public Nullable<int> EntityPropertyId { get; set; }
    	[DataMember]
        public Nullable<int> EntityPropertyToWriteId { get; set; }
    	[DataMember]
        public string Format { get; set; }
    
        [DataMember]
        public virtual EntityProperty EntityProperty { get; set; }
        [DataMember]
        public virtual EntityProperty EntityPropertyToWrite { get; set; }
    }
}
