//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class FactsetPortfolio
    {
    	[DataMember]
        public int FactSetPortfolioId { get; set; }
    	[DataMember]
        public int FundId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public int CurrencyId { get; set; }
    	[DataMember]
        public string InstrumentName { get; set; }
    	[DataMember]
        public string OriginalIdentifier { get; set; }
    	[DataMember]
        public Nullable<int> InstrumentMarketId { get; set; }
    	[DataMember]
        public Nullable<int> InstrumentClassId { get; set; }
    	[DataMember]
        public Nullable<int> FMContId { get; set; }
    	[DataMember]
        public Nullable<decimal> ReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> PriceReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> CurrencyReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> CarryReturnContribution { get; set; }
    	[DataMember]
        public bool IsItd { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserId { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    
        [DataMember]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [DataMember]
        public virtual Fund Fund { get; set; }
        [DataMember]
        public virtual InstrumentClass InstrumentClass { get; set; }
        [DataMember]
        public virtual InstrumentMarket InstrumentMarket { get; set; }
    }
}
