//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class FactsetPortfolio
    {
    	[DataMember]
        public int FactSetPortfolioId { get; set; }
    	[DataMember]
        public int FundId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public Nullable<int> InstrumentMarketId { get; set; }
    	[DataMember]
        public string InstrumentName { get; set; }
    	[DataMember]
        public string Identifier { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserId { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public int CurrencyId { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayPriceReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayCurrencyReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> TodayCarryReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDPriceReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDCurrencyReturnContribution { get; set; }
    	[DataMember]
        public Nullable<decimal> ITDCarryReturnContribution { get; set; }
    
        [DataMember]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [DataMember]
        public virtual Fund Fund { get; set; }
        [DataMember]
        public virtual InstrumentMarket InstrumentMarket { get; set; }
    }
}
