//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Financing
    {
    	[DataMember]
        public int FinancingId { get; set; }
    	[DataMember]
        public int FundId { get; set; }
    	[DataMember]
        public int InstrumentMarketId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public int CurrencyId { get; set; }
    	[DataMember]
        public int CustodianId { get; set; }
    	[DataMember]
        public decimal NetPosition { get; set; }
    	[DataMember]
        public decimal Price { get; set; }
    	[DataMember]
        public decimal Notional { get; set; }
    	[DataMember]
        public decimal BenchmarkRate { get; set; }
    	[DataMember]
        public decimal Spread { get; set; }
    	[DataMember]
        public decimal AllInRate { get; set; }
    	[DataMember]
        public decimal BenchmarkAccrual { get; set; }
    	[DataMember]
        public decimal SpreadAccrual { get; set; }
    	[DataMember]
        public decimal AllInAccrual { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public bool IsOverBorrow { get; set; }
    
        [DataMember]
        public virtual Currency Currency { get; set; }
        [DataMember]
        public virtual Custodian Custodian { get; set; }
        [DataMember]
        public virtual Fund Fund { get; set; }
        [DataMember]
        public virtual InstrumentMarket InstrumentMarket { get; set; }
    }
}
