//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Financing
    {
    	
        public Financing()
        {
            this.RawFinancings = new List<RawFinancing>();
        }
    
    	[DataMember]
        public int FinancingId { get; set; }
    	[DataMember]
        public int FundId { get; set; }
    	[DataMember]
        public int InstrumentMarketId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public int CurrencyId { get; set; }
    	[DataMember]
        public int CustodianId { get; set; }
    	[DataMember]
        public Nullable<decimal> NetPosition { get; set; }
    	[DataMember]
        public Nullable<decimal> Price { get; set; }
    	[DataMember]
        public Nullable<decimal> Notional { get; set; }
    	[DataMember]
        public Nullable<decimal> FinancingRate { get; set; }
    	[DataMember]
        public Nullable<decimal> BorrowRate { get; set; }
    	[DataMember]
        public Nullable<decimal> FinancingAccrual { get; set; }
    	[DataMember]
        public Nullable<decimal> BorrowAccrual { get; set; }
    	[DataMember]
        public decimal AllInAccrual { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public Nullable<decimal> OverborrowNotional { get; set; }
    	[DataMember]
        public Nullable<decimal> OverborrowUnits { get; set; }
    	[DataMember]
        public Nullable<decimal> OverborrowRate { get; set; }
    	[DataMember]
        public Nullable<decimal> OverborrowAccrual { get; set; }
    	[DataMember]
        public Nullable<decimal> MarginInterest { get; set; }
    	[DataMember]
        public Nullable<decimal> CashInterest { get; set; }
    	[DataMember]
        public Nullable<decimal> RehypothecationEarning { get; set; }
    	[DataMember]
        public Nullable<decimal> CashInterestRate { get; set; }
    	[DataMember]
        public Nullable<decimal> CashBalance { get; set; }
    	[DataMember]
        public Nullable<decimal> MarginBalance { get; set; }
    	[DataMember]
        public Nullable<decimal> CashInterestCredit { get; set; }
    	[DataMember]
        public Nullable<decimal> MarginRequirement { get; set; }
    	[DataMember]
        public Nullable<decimal> SwapFinancingCashBalanceDebit { get; set; }
    	[DataMember]
        public Nullable<decimal> SwapFinancingCashBalanceCredit { get; set; }
    	[DataMember]
        public Nullable<decimal> CashInterestDebit { get; set; }
    	[DataMember]
        public Nullable<decimal> RehypothecationValue { get; set; }
    	[DataMember]
        public Nullable<decimal> RehypothecationUnits { get; set; }
    	[DataMember]
        public Nullable<decimal> MarginRequirementRate { get; set; }
    	[DataMember]
        public Nullable<decimal> MarginRequirementNotional { get; set; }
    	[DataMember]
        public Nullable<decimal> SwapFinancingCashInterestRateDebit { get; set; }
    	[DataMember]
        public Nullable<decimal> SwapFinancingCashInterestRateCredit { get; set; }
    	[DataMember]
        public bool IsDummy { get; set; }
    	[DataMember]
        public Nullable<decimal> LoanedPortfolioUnits { get; set; }
    	[DataMember]
        public Nullable<decimal> LoanedPortfolioNotional { get; set; }
    	[DataMember]
        public Nullable<decimal> LoanedPortfolioGrossFee { get; set; }
    	[DataMember]
        public Nullable<decimal> LoanedPortfolioRate { get; set; }
    
        [DataMember]
        public virtual Currency Currency { get; set; }
        [DataMember]
        public virtual Custodian Custodian { get; set; }
        [DataMember]
        public virtual Fund Fund { get; set; }
        [DataMember]
        public virtual InstrumentMarket InstrumentMarket { get; set; }
        [DataMember]
        public virtual List<RawFinancing> RawFinancings { get; set; }
    }
}
