//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class ForwardFX
    {
    	[DataMember]
        public int InstrumentId { get; set; }
    	[DataMember]
        public int BaseCurrencyId { get; set; }
    	[DataMember]
        public int ContraCurrencyId { get; set; }
    	[DataMember]
        public bool IsProp { get; set; }
    	[DataMember]
        public System.DateTime MaturityDate { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    
        [DataMember]
        public virtual Currency BaseCurrency { get; set; }
        [DataMember]
        public virtual Currency ContraCurrency { get; set; }
    }
}
