//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class FundCapitalChange
    {
    	[DataMember]
        public int FundId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public decimal MarketValue { get; set; }
    	[DataMember]
        public Nullable<decimal> CapitalChange { get; set; }
    	[DataMember]
        public Nullable<decimal> OfficialNav { get; set; }
    	[DataMember]
        public Nullable<decimal> ParentMarketValue { get; set; }
    }
}
