//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HistoricEzeCommissionRate
    {
    	[DataMember]
        public int HistoricEzeCommissionRateId { get; set; }
    	[DataMember]
        public string EzeBrokerCode { get; set; }
    	[DataMember]
        public Nullable<decimal> Execution01Jan15 { get; set; }
    	[DataMember]
        public Nullable<decimal> Research01Jan15 { get; set; }
    	[DataMember]
        public Nullable<decimal> Execution01Feb16 { get; set; }
    	[DataMember]
        public Nullable<decimal> Research01Feb16 { get; set; }
    	[DataMember]
        public Nullable<decimal> Execution19Jul17 { get; set; }
    	[DataMember]
        public Nullable<decimal> Research19Jul17 { get; set; }
    	[DataMember]
        public Nullable<decimal> Execution05Sep17 { get; set; }
    	[DataMember]
        public Nullable<decimal> Research05Sep17 { get; set; }
    	[DataMember]
        public Nullable<decimal> Execution20Oct17 { get; set; }
    	[DataMember]
        public Nullable<decimal> Research20Oct17 { get; set; }
    	[DataMember]
        public bool IsResearchUSTrade { get; set; }
    	[DataMember]
        public bool IsResearchAllCFDTrade { get; set; }
    	[DataMember]
        public bool IsResearchUSHKCNCFDTrade { get; set; }
    	[DataMember]
        public bool IsResearchUSHKCNCFDTrade2016 { get; set; }
    	[DataMember]
        public bool IsResearchAllCFDTrade2016 { get; set; }
    }
}
