//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class IndexConstituent
    {
    	[DataMember]
        public int IndexConstituentId { get; set; }
    	[DataMember]
        public int InstrumentId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public decimal Weighting { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public Nullable<decimal> Price { get; set; }
    	[DataMember]
        public Nullable<decimal> TotalReturn { get; set; }
    	[DataMember]
        public string BloombergTicker { get; set; }
    	[DataMember]
        public Nullable<decimal> RebasedPrice { get; set; }
    	[DataMember]
        public int ConstituentInstrumentMarketId { get; set; }
    }
}
