//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using TypeLite;
    [TsClass]
    [DataContract(IsReference = true)]
    public partial class PADealingAccount
    {
    	[DataMember]
        public int PADealingAccountID { get; set; }
    	[DataMember]
        public int UserID { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Number { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public int PADealingBrokerId { get; set; }
    
        [DataMember]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [DataMember]
        public virtual PADealingBroker PADealingBroker { get; set; }
    }
}
