//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class RawFXRate
    {
    	
        public RawFXRate()
        {
            this.FromFXRates = new List<FXRate>();
            this.ToFXRates = new List<FXRate>();
            this.FromSecondFXRates = new List<FXRate>();
            this.ToSecondFXRates = new List<FXRate>();
        }
    
    	[DataMember]
        public int RawFXRateId { get; set; }
    	[DataMember]
        public System.DateTime ReferenceDate { get; set; }
    	[DataMember]
        public System.DateTime ForwardDate { get; set; }
    	[DataMember]
        public int EntityRankingSchemeItemId { get; set; }
    	[DataMember]
        public decimal BidValue { get; set; }
    	[DataMember]
        public System.DateTime BidUpdateDate { get; set; }
    	[DataMember]
        public decimal AskValue { get; set; }
    	[DataMember]
        public System.DateTime AskUpdateDate { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public int CurrencyId { get; set; }
    
        [DataMember]
        public virtual List<FXRate> FromFXRates { get; set; }
        [DataMember]
        public virtual List<FXRate> ToFXRates { get; set; }
        [DataMember]
        public virtual List<FXRate> FromSecondFXRates { get; set; }
        [DataMember]
        public virtual List<FXRate> ToSecondFXRates { get; set; }
    }
}
