//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odey.Framework.Keeley.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class Research
    {
    	
        public Research()
        {
            this.ResearchAttachments = new List<ResearchAttachment>();
            this.ResearchInstrumentMarkets = new List<ResearchInstrumentMarket>();
        }
    
    	[DataMember]
        public int ResearchId { get; set; }
    	[DataMember]
        public string Subject { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CodeRedId { get; set; }
    	[DataMember]
        public System.DateTime StartDt { get; set; }
    	[DataMember]
        public int UpdateUserID { get; set; }
    	[DataMember]
        public byte[] DataVersion { get; set; }
    	[DataMember]
        public System.DateTime CreatedDt { get; set; }
    	[DataMember]
        public byte[] Document { get; set; }
    	[DataMember]
        public Nullable<int> CountryId { get; set; }
    	[DataMember]
        public string AdditionalKeyWords { get; set; }
    	[DataMember]
        public int ContributorId { get; set; }
    	[DataMember]
        public Nullable<int> GicsId { get; set; }
    	[DataMember]
        public Nullable<int> ActionFlags { get; set; }
    	[DataMember]
        public bool IsActioned { get; set; }
    	[DataMember]
        public Nullable<bool> IsCRGResearch { get; set; }
    
        [DataMember]
        public virtual List<ResearchAttachment> ResearchAttachments { get; set; }
        [DataMember]
        public virtual List<ResearchInstrumentMarket> ResearchInstrumentMarkets { get; set; }
        [DataMember]
        public virtual Country Country { get; set; }
        [DataMember]
        public virtual Industry GicsSector { get; set; }
        [DataMember]
        public virtual Industry Industry { get; set; }
        [DataMember]
        public virtual ResearchContributor ResearchContributor { get; set; }
    }
}
