using System.Runtime.Serialization;

namespace Odey.Framework.Keeley.Entities.Enums
{
    [DataContract]
    public enum CountryIds
    {
        [EnumMember]
        None = 0,
        [EnumMember]
        Unknown = 1,
        [EnumMember]
        GreatBritain = 62,
        [EnumMember]
        Ireland = 56,
        [EnumMember]
        UnitedStates = 53,
        [EnumMember]
        Australia = 55,
        [EnumMember]
        China = 57,
        [EnumMember]
        HongKong = 58,
        [EnumMember]
        Canada = 68,
        [EnumMember]
        Argentina = 111,
        [EnumMember]
        Russia = 92,
        [EnumMember]
        Andorra = 127,
        [EnumMember] Austria = 60,
        [EnumMember] Bahamas = 120,
        [EnumMember] Bahrain = 136,
        [EnumMember] Barbados = 145,
        [EnumMember] Belgium = 69,
        [EnumMember] Belize = 147,
        [EnumMember] Bermuda = 61,
        [EnumMember] Brazil = 79,
        [EnumMember] Bulgaria = 160,
        [EnumMember] CaymanIslands = 63,
        [EnumMember] Chile = 165,
        [EnumMember] Colombia = 155,
        [EnumMember] CookIslands = 128,
        [EnumMember] Croatia = 96,
        [EnumMember] Cyprus = 84,
        [EnumMember] CzechRepublic = 91,
        [EnumMember] Czechoslovakia = 117,
        [EnumMember] Denmark = 76,
        [EnumMember] Estonia = 108,
        [EnumMember] Finland = 93,
        [EnumMember] France = 64,
        [EnumMember] Georgia = 158,
        [EnumMember] Germany = 59,
        [EnumMember] Ghana = 157,
        [EnumMember] Gibraltar = 114,
        [EnumMember] Greece = 85,
        [EnumMember] Guernsey = 98,
        [EnumMember] Hungary = 77,
        [EnumMember] Iceland = 101,
        [EnumMember] India = 67,
        [EnumMember] Indonesia = 103,
        [EnumMember] IsleofMan = 87,
        [EnumMember] Israel = 94,
        [EnumMember] Italy = 81,
        [EnumMember] Japan = 54,
        [EnumMember] Jersey = 78,
        [EnumMember] Kazachstan = 154,
        [EnumMember] Kuwait = 118,
        [EnumMember] Latvia = 161,
        [EnumMember] Liberia = 149,
        [EnumMember] Libya = 148,
        [EnumMember] Liechtenstein = 95,
        [EnumMember] Lithuania = 162,
        [EnumMember] Luxembourg = 89,
        [EnumMember] Macau = 146,
        [EnumMember] Malaysia = 105,
        [EnumMember] Malta = 125,
        [EnumMember] MarshallIslands = 135,
        [EnumMember] Mauritius = 132,
        [EnumMember] Mexico = 110,
        [EnumMember] Monaco = 133,
        [EnumMember] Mongolia = 130,
        [EnumMember] Morocco = 107,
        [EnumMember] Myanmar = 168,
        [EnumMember] NetherlandAntilles = 122,
        [EnumMember] Netherlands = 72,
        [EnumMember] NewCaledonia = 126,
        [EnumMember] NewZealand = 100,
        [EnumMember] Nigeria = 102,
        [EnumMember] Norway = 80,
        [EnumMember] Oman = 137,
        [EnumMember] Other = 1,
        [EnumMember] OtherAsiaExclJapan = 140,
        [EnumMember] OtherEurope = 113,
        [EnumMember] OtherGlobal = 139,
        [EnumMember] OtherLatinAmerica = 142,
        [EnumMember] OtherNorthAmerica = 152,
        [EnumMember] Pakistan = 106,
        [EnumMember] Panama = 123,
        [EnumMember] Paraguay = 159,
        [EnumMember] Peru = 71,
        [EnumMember] Philippines = 99,
        [EnumMember] Poland = 88,
        [EnumMember] Portugal = 86,
        [EnumMember] Qatar = 115,
        [EnumMember] Romania = 163,
        [EnumMember] RussianFederation = 92,
        [EnumMember] SaudiArabia = 143,
        [EnumMember] Senegal = 138,
        [EnumMember] Singapore = 82,
        [EnumMember] Slovakia = 164,
        [EnumMember] Slovenia = 156,
        [EnumMember] Somalia = 119,
        [EnumMember] SouthAfrica = 83,
        [EnumMember] SouthKorea = 75,
        [EnumMember] Spain = 74,
        [EnumMember] Sweden = 70,
        [EnumMember] Switzerland = 73,
        [EnumMember] Taiwan = 66,
        [EnumMember] Tanzania = 134,
        [EnumMember] Thailand = 104,
        [EnumMember] Turkey = 65,
        [EnumMember] Ukraine = 167,
        [EnumMember] UnitedArabEmirates = 109,
        [EnumMember] Uruguay = 169,
        [EnumMember] Vietnam = 151

    }
}
